[2024-12-14T11:21:01.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T11:21:01.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_instruction_fact manual__2024-12-14T11:20:47.303390+00:00 [queued]>
[2024-12-14T11:21:01.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_instruction_fact manual__2024-12-14T11:20:47.303390+00:00 [queued]>
[2024-12-14T11:21:01.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T11:21:01.722+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_instruction_fact> on 2024-12-14 11:20:47.303390+00:00
[2024-12-14T11:21:01.731+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=564) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T11:21:01.733+0000] {standard_task_runner.py:63} INFO - Started process 566 to run task
[2024-12-14T11:21:01.732+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_instruction_fact', 'manual__2024-12-14T11:20:47.303390+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmp5fkomw_1']
[2024-12-14T11:21:01.735+0000] {standard_task_runner.py:91} INFO - Job 118: Subtask insert_data.insert_data_instruction_fact
[2024-12-14T11:21:01.792+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_instruction_fact manual__2024-12-14T11:20:47.303390+00:00 [running]> on host 472b63b715e1
[2024-12-14T11:21:01.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_instruction_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T11:20:47.303390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T11:20:47.303390+00:00'
[2024-12-14T11:21:01.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T11:21:02.313+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-14T11:21:02.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T11:21:02.328+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_instruction_fact, run_id=manual__2024-12-14T11:20:47.303390+00:00, execution_date=20241214T112047, start_date=20241214T112101, end_date=20241214T112102
[2024-12-14T11:21:02.356+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-14T11:21:02.403+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-14T11:21:02.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
