[2024-12-13T20:27:33.822+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-13T20:27:34.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-13T20:27:15.522338+00:00 [queued]>
[2024-12-13T20:27:34.040+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-13T20:27:15.522338+00:00 [queued]>
[2024-12-13T20:27:34.040+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-13T20:27:34.051+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_enrollment_fact> on 2024-12-13 20:27:15.522338+00:00
[2024-12-13T20:27:34.059+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5429) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-13T20:27:34.061+0000] {standard_task_runner.py:63} INFO - Started process 5431 to run task
[2024-12-13T20:27:34.068+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_enrollment_fact', 'manual__2024-12-13T20:27:15.522338+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpq1up06qu']
[2024-12-13T20:27:34.074+0000] {standard_task_runner.py:91} INFO - Job 547: Subtask insert_data.insert_data_enrollment_fact
[2024-12-13T20:27:34.171+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-13T20:27:15.522338+00:00 [running]> on host 1fe973f28a1c
[2024-12-13T20:27:34.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_enrollment_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T20:27:15.522338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T20:27:15.522338+00:00'
[2024-12-13T20:27:34.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-13T20:27:34.759+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-13T20:27:34.761+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-13T20:27:34.781+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_enrollment_fact, run_id=manual__2024-12-13T20:27:15.522338+00:00, execution_date=20241213T202715, start_date=20241213T202734, end_date=20241213T202734
[2024-12-13T20:27:34.805+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-13T20:27:34.852+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-13T20:27:34.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
