[2024-12-14T10:48:33.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-14T10:48:33.212+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-14T10:48:15.579528+00:00 [queued]>
[2024-12-14T10:48:33.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-14T10:48:15.579528+00:00 [queued]>
[2024-12-14T10:48:33.222+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-14T10:48:33.236+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_enrollment_fact> on 2024-12-14 10:48:15.579528+00:00
[2024-12-14T10:48:33.244+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=479) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-14T10:48:33.245+0000] {standard_task_runner.py:63} INFO - Started process 481 to run task
[2024-12-14T10:48:33.249+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_enrollment_fact', 'manual__2024-12-14T10:48:15.579528+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmpexkt49qe']
[2024-12-14T10:48:33.253+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask insert_data.insert_data_enrollment_fact
[2024-12-14T10:48:33.315+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_enrollment_fact manual__2024-12-14T10:48:15.579528+00:00 [running]> on host 06cbf31e97a5
[2024-12-14T10:48:33.579+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_enrollment_fact' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T10:48:15.579528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-14T10:48:15.579528+00:00'
[2024-12-14T10:48:33.581+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-14T10:48:33.944+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-14T10:48:33.945+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-14T10:48:33.956+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_enrollment_fact, run_id=manual__2024-12-14T10:48:15.579528+00:00, execution_date=20241214T104815, start_date=20241214T104833, end_date=20241214T104833
[2024-12-14T10:48:33.983+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-14T10:48:34.054+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-14T10:48:34.061+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
