[2024-12-15T08:22:58.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-15T08:22:58.845+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-15T08:22:56.784468+00:00 [queued]>
[2024-12-15T08:22:58.854+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-15T08:22:56.784468+00:00 [queued]>
[2024-12-15T08:22:58.854+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-15T08:22:58.869+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_data.insert_data_course> on 2024-12-15 08:22:56.784468+00:00
[2024-12-15T08:22:58.880+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-15T08:22:58.881+0000] {standard_task_runner.py:63} INFO - Started process 3471 to run task
[2024-12-15T08:22:58.882+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data', 'insert_data.insert_data_course', 'manual__2024-12-15T08:22:56.784468+00:00', '--job-id', '505', '--raw', '--subdir', 'DAGS_FOLDER/etl_data.py', '--cfg-path', '/tmp/tmp4i_22wpj']
[2024-12-15T08:22:58.885+0000] {standard_task_runner.py:91} INFO - Job 505: Subtask insert_data.insert_data_course
[2024-12-15T08:22:58.929+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data.insert_data.insert_data_course manual__2024-12-15T08:22:56.784468+00:00 [running]> on host 2f4e9c743994
[2024-12-15T08:22:59.017+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data' AIRFLOW_CTX_TASK_ID='insert_data.insert_data_course' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T08:22:56.784468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T08:22:56.784468+00:00'
[2024-12-15T08:22:59.018+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-15T08:22:59.369+0000] {__init__.py:412} INFO - GETFILESTATUS /data/raw/course/ user.name=default namenode:9870
[2024-12-15T08:22:59.389+0000] {__init__.py:412} INFO - CREATE /data/raw/course/course_1734250979.csv overwrite=True async_=True user.name=default namenode:9870
[2024-12-15T08:22:59.494+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-15T08:22:59.494+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-15T08:22:59.514+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data, task_id=insert_data.insert_data_course, run_id=manual__2024-12-15T08:22:56.784468+00:00, execution_date=20241215T082256, start_date=20241215T082258, end_date=20241215T082259
[2024-12-15T08:22:59.585+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-15T08:22:59.647+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-15T08:22:59.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
